### ISSUE TITLE
EMR support?

### ISSUE THREAD

**Issue by fdosani** [capitalone/Particle-Cloud-Framework#1]
This looks cool. I'm wondering if there might be EMR support coming down the pipeline? 
If not it would be something maybe I can PR over? Thanks!

**Comment by anovis** [comment]
we actually have a particle mostly done. working on the tests for it now, so hopefully can get that out by the end of the week!

**Comment by anovis** [comment]
we merged the emr feature into dev. #4 . the release is `0.1.1.dev1`. it was a pretty tricky particle so let us know if you run into any errors. the only updates implemented now are for the instance group count and instance fleet desired dedicated instances.
