### ISSUE TITLE
IAM particles support

### ISSUE THREAD

**Issue by Asterazor** [capitalone/Particle-Cloud-Framework#10]
Are there plans to support IAM particles (i.e. role, policies, etc) as outlined by [boto](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html)?

**Comment by anovis** [comment]
yes. we had it in our backlog. We will add to this sprint. both iam role and iam policies.

**Comment by anovis** [comment]
#24 #21
