### ISSUE TITLE
botocore version conflict in requirements

### ISSUE THREAD

**Issue by eloucks** [capitalone/Particle-Cloud-Framework#12]
A vanilla install of the requirements file from the repo shows a conflict in the version of botocore:

`boto3 1.8.5 has requirement botocore<1.12.0,>=1.11.5, but you'll have botocore 1.10.67 which is incompatible.`

I'm guessing this is because of the issue with moto that will cause test failures with the more recent botocore version.

**Comment by anovis** [comment]
the newer botocore versions broke a bunch of our tests. I believe botocore and moto have fixed some of these issues so I will review and update

**Comment by anovis** [comment]
looks like botocore==1.12.72 fixed some of the issues. the tests all passed. will create a pr for it.

**Comment by eloucks** [comment]
Awesome, thanks! :shipit:

**Comment by anovis** [comment]
uses 1.12.72 which is tied to awscli and boto3 versions.
