### ISSUE TITLE
Error handles for Quasiparticle sync issues

### ISSUE THREAD

**Issue by tonyx93** [capitalone/Particle-Cloud-Framework#22]
I think it makes sense to add an argument to `Quasiparticle.apply()` to allow it to raise any underlying errors if an issue occurs. 
Currently, the error is logged and swallowed.
This will improve transparency and allow developers to add custom error handling if need be

https://github.com/capitalone/Particle-Cloud-Framework/blob/master/pcf/core/quasiparticle.py#L121
In this except block, we can add something like:
```
if report_errors:
  raise error
```

**Comment by anovis** [comment]
the error should be getting logged and viewable for the user. you have to set up the logger which is a little unclear.

the below should log everything. i think to view the errors  level=logging.INFO should be enough to get it. 

https://capitalone.github.io/Particle-Cloud-Framework/docs/build/html/sections/quickstart.html#logging
```
import logging

logging.basicConfig(level=logging.DEBUG)

for handler in logging.root.handlers:
    handler.addFilter(logging.Filter('pcf'))
```

i agree we need to have a better logging system going forward.

**Comment by tonyx93** [comment]
Yeah, I have no issues getting the log
But it'll be nice if I could configure `apply()` to raise an error if there are an internal issues in case I want to implement custom error handling
For example, in AWS, our account if configured to allow at most 1 x1.16xlarge EC2 instances running at one time. So if I configure an quasiparticle that contains a x1.16xlarge EC2 instance when another instance is already running, `apply()` will fail silently because the quasiparticle is unable to create the instance.
However, I wish to forward the internal error message when `apply()` fails. I currently can't do that because `apply()` fails silently. I wish to wrap `apply()` in an `except` block so that I can retrieve the root error.

**Comment by anovis** [comment]
got it. we actually ran into that issue ourselves recently. we will have a pr for it shortly. 
so quasiparticles will raise any errors that happen in the particle.

**Comment by anovis** [comment]
#8 this pr has a change to raise errors in quasiparticles that occur in particles.
