### ISSUE TITLE
Incompatibilities with python 3.4 and 3.5

### ISSUE THREAD

**Issue by jacoblearned** [capitalone/Particle-Cloud-Framework#39]
#### Python 3.4 - version conflicts for `six` and incompatible function parameter in `setup.py` for 3.4
[Travis build for 3.4 demonstrating this incompatibility](https://travis-ci.org/capitalone/Particle-Cloud-Framework/jobs/486574520)

#### Python 3.5 - Single test failure for parent-child Particle variables
[Travis build for 3.5 demonstrating this incompatibility](https://travis-ci.org/capitalone/Particle-Cloud-Framework/jobs/486574519)

**Comment by anovis** [comment]
yes we assume python > 3.6. right @elo

we should document this.

**Comment by ethanwlo** [comment]
Correct. PCF was built with Python 3.6 from the get-go and we assume users will use Python 3.6+. We should add that to the doc.

**Comment by anovis** [comment]
#50
