### ISSUE TITLE
Logs for error handling should be at least be "WARNING" level

### ISSUE THREAD

**Issue by tonyx93** [capitalone/Particle-Cloud-Framework#58]
https://github.com/capitalone/Particle-Cloud-Framework/blob/5180d138a600130bffec22997b7a1f69c873c5ab/pcf/core/quasiparticle.py#L123-L130

**Comment by tonyx93** [comment]
should be `logger.warning()` or `logger.error()`

**Comment by anovis** [comment]
you are right it should not be be `logger.info`. To be consistent with logging in particle.py I will change to `logger.debug`. the rollback can still be `logger.info` but should be more descriptive

**Comment by anovis** [comment]
#59
