### ISSUE TITLE
Proposal - move resources into separate folder

### ISSUE THREAD

**Issue by anovis** [capitalone/Particle-Cloud-Framework#94]
not sure if we want all the resources to be in core. might be easier for the user if there was a separate folder in core where all the resources are kept. 

```core -> resources -> aws_resource, azure_resource, docker_resource``` ... 

thoughts?

**Comment by ethanwlo** [comment]
It would be consistent with how we structure particles. However, would we ever need to have more than one file per resource? If not, it might be an overkill.

**Comment by anovis** [comment]
yeah thats true. not sure how many other resources we will have. will close for now. if we have a few more maybe we can revisit
